/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VIEW;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Model.Jadwal_halte;
import Model.Database;
 
/**
 *
 * @author Luqman
 */
public class Crud_admin extends javax.swing.JFrame {
    private DefaultTableModel model;
    
    

    /**
     * Creates new form crud_jadwal_admin
     */
    public Crud_admin() {
        initComponents();
        Database.connect();
        tabel();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    final void tabel(){
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Halte Keberangkatan");
        model.addColumn("Halte Tiba");
        model.addColumn("Waktu Keberangkatan");
        model.addColumn("Waktu Tiba");
        
            try {
            Statement statement = Database.connection.createStatement();
            ResultSet resultSet = statement.executeQuery("SELECT * FROM jadwal_halte");

    while (resultSet.next()) {
        
        model.addRow(new Object[] {
            resultSet.getString("halte_keberangkatan"),
            resultSet.getString("halte_tiba"),
            resultSet.getString("waktu_keberangkatan"),
            resultSet.getString("waktu_tiba")
        });
         tabelJadwalHalte.setModel(model);
    } 
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Gagal memuat data!");
            }
         }
        void clearText(){
        Halte_Keberangkatan.setText("");
        Halte_tiba.setText("");
        Waktu_Keberangkatan.setText("");
        Waktu_Tiba.setText("");
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Halte_Keberangkatan = new javax.swing.JTextField();
        Halte_tiba = new javax.swing.JTextField();
        Waktu_Keberangkatan = new javax.swing.JTextField();
        Waktu_Tiba = new javax.swing.JTextField();
        Keluar = new javax.swing.JButton();
        jButton_hapus = new javax.swing.JButton();
        jButton_tambah = new javax.swing.JButton();
        jButton_simpan_edit = new javax.swing.JButton();
        jButton_Refresh = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelJadwalHalte = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1200, 750));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Waktu Tiba                    :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 220, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Halte keberangkatan    : ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Halte tiba                       :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Waktu keberangkatan  : ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 190, -1, -1));

        Halte_Keberangkatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Halte_KeberangkatanActionPerformed(evt);
            }
        });
        getContentPane().add(Halte_Keberangkatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 190, 190, -1));

        Halte_tiba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Halte_tibaActionPerformed(evt);
            }
        });
        getContentPane().add(Halte_tiba, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 220, 190, -1));

        Waktu_Keberangkatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Waktu_KeberangkatanActionPerformed(evt);
            }
        });
        getContentPane().add(Waktu_Keberangkatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 190, 180, -1));

        Waktu_Tiba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Waktu_TibaActionPerformed(evt);
            }
        });
        getContentPane().add(Waktu_Tiba, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 220, 180, -1));

        Keluar.setText("Keluar");
        Keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KeluarActionPerformed(evt);
            }
        });
        getContentPane().add(Keluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, -1, -1));

        jButton_hapus.setText("Hapus");
        jButton_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_hapusActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 320, -1, -1));

        jButton_tambah.setText("Tambah");
        jButton_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_tambahActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_tambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 320, -1, -1));

        jButton_simpan_edit.setText("Simpan Edit");
        jButton_simpan_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_simpan_editActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_simpan_edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 320, -1, -1));

        jButton_Refresh.setText("Refresh");
        jButton_Refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_RefreshActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 320, -1, -1));

        tabelJadwalHalte.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Halte Awal", "Halte Tujuan", "Waktu Keberangkatan", "Waktu Tiba"
            }
        ));
        tabelJadwalHalte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelJadwalHalteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelJadwalHalte);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 360, 770, 310));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/page/crud_jadwal_admin.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_simpan_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_simpan_editActionPerformed
           try {
           int row = tabelJadwalHalte.getSelectedRow();
            
            if (row == -1) {
        JOptionPane.showMessageDialog(null, "Silahkan pilih baris yang akan diubah!");
        } else {
       
        
        String halteKeberangkatan = Halte_Keberangkatan.getText();
        String halteTiba = Halte_tiba.getText();
        String waktuKeberangkatan = Waktu_Keberangkatan.getText();
        String waktuTiba = Waktu_Tiba.getText();
              if ( halteKeberangkatan.isEmpty() || halteTiba.isEmpty() || waktuKeberangkatan.isEmpty() || waktuTiba.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Tolong isi semua kolom");
        } else {
           
            Jadwal_halte jadwal_halte = new Jadwal_halte(halteKeberangkatan, halteTiba, waktuKeberangkatan, waktuTiba);
            JOptionPane.showMessageDialog(null, "berhasil di ubah");
            jadwal_halte.updateJadwalHalte(); 

            tabel();
            clearText();
        }
    }
} catch (Exception e) {
    JOptionPane.showMessageDialog(null, "Terjadi Kesalahan");
    e.printStackTrace();
}
// TODO add your handling code here:
    }//GEN-LAST:event_jButton_simpan_editActionPerformed

    private void jButton_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_tambahActionPerformed
       try {
        String halteKeberangkatan = Halte_Keberangkatan.getText();
        String halteTiba = Halte_tiba.getText();
        String waktuKeberangkatan = Waktu_Keberangkatan.getText();
        String waktuTiba = Waktu_Tiba.getText();
         if ( halteKeberangkatan.isEmpty() || halteTiba.isEmpty() || waktuKeberangkatan.isEmpty() || waktuTiba.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Data tidak lengkap!");
        } else {
           Jadwal_halte jadwal_halte = new Jadwal_halte(halteKeberangkatan, halteTiba, waktuKeberangkatan, waktuTiba);
            jadwal_halte.createJadwalHalte();
            JOptionPane.showMessageDialog(null, "Berhasil di tambahkan");
            tabel();  
            clearText(); 
    }
} catch (Exception e) {
    JOptionPane.showMessageDialog(null, "Terjadi Kesalahan!" + e.getMessage());
}
// TODO add your handling code here:
    }//GEN-LAST:event_jButton_tambahActionPerformed

    private void jButton_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_hapusActionPerformed
       try {
            int row = tabelJadwalHalte.getSelectedRow();

            if (row == -1) {
                JOptionPane.showMessageDialog(null, "Silahkan pilih baris yang akan dihapus");
            } else {
                DefaultTableModel model = (DefaultTableModel) tabelJadwalHalte.getModel();
                String halte_keberangkatan = tabelJadwalHalte.getValueAt(row, 0).toString();
                Jadwal_halte jadwal_halte = new Jadwal_halte("","","","");
                jadwal_halte.setHalte_keberangkatan(halte_keberangkatan);
                jadwal_halte.deleteJadwalHalte();
                model.removeRow(row);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Terjadi Kesalahan");
//            e.printStackTrace();
        }      
// TODO add your handling code here:
    }//GEN-LAST:event_jButton_hapusActionPerformed

    private void KeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KeluarActionPerformed
        Landing_home landing_home = new Landing_home();
        landing_home.setVisible(true);
        landing_home.setLocationRelativeTo(null);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_KeluarActionPerformed

    private void Waktu_KeberangkatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Waktu_KeberangkatanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Waktu_KeberangkatanActionPerformed

    private void Halte_KeberangkatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Halte_KeberangkatanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Halte_KeberangkatanActionPerformed

    private void Halte_tibaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Halte_tibaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Halte_tibaActionPerformed

    private void Waktu_TibaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Waktu_TibaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Waktu_TibaActionPerformed

    private void jButton_RefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_RefreshActionPerformed
        tabel();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_RefreshActionPerformed

    private void tabelJadwalHalteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelJadwalHalteMouseClicked
 int row = tabelJadwalHalte.getSelectedRow();

    // Mendapatkan data dari tabel berdasarkan baris yang diklik
    String halteKeberangkatan = tabelJadwalHalte.getValueAt(row, 0).toString();
    String halteTiba = tabelJadwalHalte.getValueAt(row, 1).toString();
    String waktuKeberangkatan = tabelJadwalHalte.getValueAt(row, 2).toString();
    String waktuTiba = tabelJadwalHalte.getValueAt(row, 3).toString();

    // Menampilkan data ke komponen GUI
    Halte_Keberangkatan.setText(halteKeberangkatan);
    Halte_tiba.setText(halteTiba);
    Waktu_Keberangkatan.setText(waktuKeberangkatan);
    Waktu_Tiba.setText(waktuTiba);
// TODO add your handling code here:
    }//GEN-LAST:event_tabelJadwalHalteMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Crud_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Crud_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Crud_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Crud_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Halte_Keberangkatan;
    private javax.swing.JTextField Halte_tiba;
    private javax.swing.JButton Keluar;
    private javax.swing.JTextField Waktu_Keberangkatan;
    private javax.swing.JTextField Waktu_Tiba;
    private javax.swing.JButton jButton_Refresh;
    private javax.swing.JButton jButton_hapus;
    private javax.swing.JButton jButton_simpan_edit;
    private javax.swing.JButton jButton_tambah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelJadwalHalte;
    // End of variables declaration//GEN-END:variables
}
