/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VIEW;
import Model.Database;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Luqman
 */
public class Dasboard_pengguna extends javax.swing.JFrame {

    /**
     * Creates new form Dasboard_pengguna
     */
    public Dasboard_pengguna() {
        initComponents();
        Database.connect();
        tabel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
        final void tabel(){
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Halte Keberangkatan");
        model.addColumn("Halte Tiba");
        model.addColumn("Waktu Keberangkatan");
        model.addColumn("Waktu Tiba");
        
            try {
            Statement statement = Database.connection.createStatement();
            ResultSet resultSet = statement.executeQuery("SELECT * FROM jadwal_halte");

    while (resultSet.next()) {
        
        model.addRow(new Object[] {
            resultSet.getString("halte_keberangkatan"),
            resultSet.getString("halte_tiba"),
            resultSet.getString("waktu_keberangkatan"),
            resultSet.getString("waktu_tiba")
        });
         tabelJadwalHalte.setModel(model);
    } 
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Gagal memuat data!");
            }
         }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        searching_pengguna = new javax.swing.JButton();
        button_keluar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelJadwalHalte = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1200, 750));
        setMinimumSize(new java.awt.Dimension(1200, 750));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        searching_pengguna.setText("Jelajahi Lebih Jauh");
        searching_pengguna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searching_penggunaActionPerformed(evt);
            }
        });
        getContentPane().add(searching_pengguna, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 220, 200, 40));

        button_keluar.setText("Keluar");
        button_keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_keluarActionPerformed(evt);
            }
        });
        getContentPane().add(button_keluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, -1, -1));

        tabelJadwalHalte.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Halte Keberangkatan", "Halte Tiba", "Waktu Keberangkatan", "Waktu Tiba"
            }
        ));
        jScrollPane1.setViewportView(tabelJadwalHalte);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 310, 680, 340));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/page/searching pelanggan.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_keluarActionPerformed
        Landing_home landing_home = new Landing_home();
        landing_home.setVisible(true);
        landing_home.setLocationRelativeTo(null);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_button_keluarActionPerformed

    private void searching_penggunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searching_penggunaActionPerformed
        Menu_pengguna menu_pengguna = new Menu_pengguna();
        menu_pengguna.setVisible(true);
        menu_pengguna.setLocationRelativeTo(null);
        this.dispose();
// TODO add your handling code here:
    }//GEN-LAST:event_searching_penggunaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dasboard_pengguna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dasboard_pengguna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dasboard_pengguna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dasboard_pengguna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dasboard_pengguna().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_keluar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton searching_pengguna;
    private javax.swing.JTable tabelJadwalHalte;
    // End of variables declaration//GEN-END:variables
}
