/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VIEW;
import javax.swing.JOptionPane;

/**
 *
 * @author Luqman
 */
public class Landing_home extends javax.swing.JFrame {

    /**
     * Creates new form landing_home
     */
    public Landing_home() {
        initComponents();


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton_login_admin = new javax.swing.JButton();
        jButton_login_pengguna = new javax.swing.JButton();
        quit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1200, 750));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton_login_admin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_login_admin.setText("Login Admin");
        jButton_login_admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_login_adminActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_login_admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 570, 190, 40));

        jButton_login_pengguna.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_login_pengguna.setText("Login Pengguna");
        jButton_login_pengguna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_login_penggunaActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_login_pengguna, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 570, 180, 40));

        quit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        quit.setText("QUIT");
        quit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitActionPerformed(evt);
            }
        });
        getContentPane().add(quit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 30, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/page/landing page.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_login_adminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_login_adminActionPerformed
        Login_admin login_admin = new Login_admin();
        login_admin.setVisible(true);
        login_admin.setLocationRelativeTo(null);
        this.dispose();
        // TODO add your handling code here:
       
        
    }//GEN-LAST:event_jButton_login_adminActionPerformed

    private void jButton_login_penggunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_login_penggunaActionPerformed
        Login_pengguna login_pengguna = new Login_pengguna();
        login_pengguna.setVisible(true);
        login_pengguna.setLocationRelativeTo(null);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_login_penggunaActionPerformed

    private void quitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitActionPerformed
         JOptionPane.showMessageDialog(this, "Terima kasih telah menggunakan aplikasi ini!", "Terima Kasih", JOptionPane.INFORMATION_MESSAGE);
        System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_quitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Landing_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Landing_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Landing_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Landing_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Landing_home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_login_admin;
    private javax.swing.JButton jButton_login_pengguna;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton quit;
    // End of variables declaration//GEN-END:variables
}
