/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VIEW;
import Model.Admin;
import Model.Database;
import javax.swing.JOptionPane;


/**
 *
 * @author Luqman
 */
public class Login_admin extends javax.swing.JFrame {
    
    /**
     * Creates new form NewJFrame1
     */
    public Login_admin() {
        initComponents();
        Database.connect();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        email_admin = new javax.swing.JTextField();
        jButton_login_admin = new javax.swing.JButton();
        Password_admin = new javax.swing.JPasswordField();
        jButton_Kembali_login = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1200, 750));
        setMinimumSize(new java.awt.Dimension(1200, 750));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        email_admin.setBackground(new java.awt.Color(204, 255, 255));
        email_admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                email_adminActionPerformed(evt);
            }
        });
        getContentPane().add(email_admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 310, 240, -1));

        jButton_login_admin.setBackground(new java.awt.Color(0, 153, 255));
        jButton_login_admin.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton_login_admin.setForeground(new java.awt.Color(255, 255, 255));
        jButton_login_admin.setText("Login");
        jButton_login_admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_login_adminActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_login_admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 490, 160, 50));

        Password_admin.setBackground(new java.awt.Color(204, 255, 255));
        Password_admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Password_adminActionPerformed(evt);
            }
        });
        getContentPane().add(Password_admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 420, 240, -1));

        jButton_Kembali_login.setBackground(new java.awt.Color(51, 204, 255));
        jButton_Kembali_login.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Kembali_login.setText("Kembali");
        jButton_Kembali_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Kembali_loginActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Kembali_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 570, 80, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/page/login admin.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void email_adminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_email_adminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_email_adminActionPerformed

    private void jButton_login_adminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_login_adminActionPerformed

       try {
            String email = email_admin.getText();
            String password = Password_admin.getText();

            if (email.equals("") || password.equals("")) {
                JOptionPane.showMessageDialog(null, "Email dan Password tidak boleh kosong!");
            } else {
                if (Admin.loginAdmin(email, password)) {
                    Crud_admin crud_admin = new Crud_admin();
                    crud_admin.setVisible(true);
                    crud_admin.setLocationRelativeTo(null);
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(null, "Email dan password salah!");
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Terdapat Kesalahan: " + e.getMessage());
        }
    
    }//GEN-LAST:event_jButton_login_adminActionPerformed

    private void jButton_Kembali_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Kembali_loginActionPerformed
        Landing_home landing_home = new Landing_home();
        landing_home.setVisible(true);
        landing_home.setLocationRelativeTo(null);
        this.dispose();
        // TODO add your handling code here:

    }//GEN-LAST:event_jButton_Kembali_loginActionPerformed

    private void Password_adminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Password_adminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Password_adminActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login_admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Login_admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField Password_admin;
    private javax.swing.JTextField email_admin;
    private javax.swing.JButton jButton_Kembali_login;
    private javax.swing.JButton jButton_login_admin;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
