/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VIEW;

import javax.swing.JOptionPane;
import Model.Database;
import Model.Pengguna;

/**
 *
 * @author Luqman
 */
public class Login_pengguna extends javax.swing.JFrame {

    /**
     * Creates new form Login_Customer
     */
    public Login_pengguna() {
        initComponents();
        Database.connect();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        email_Pengguna = new javax.swing.JTextField();
        jButton_login_Pengguna = new javax.swing.JButton();
        Password_login_pengguna = new javax.swing.JPasswordField();
        jButton_Kembali_Pengguna = new javax.swing.JButton();
        buat_sekarangButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1200, 750));
        setMinimumSize(new java.awt.Dimension(1200, 750));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        email_Pengguna.setBackground(new java.awt.Color(204, 255, 255));
        email_Pengguna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                email_PenggunaActionPerformed(evt);
            }
        });
        getContentPane().add(email_Pengguna, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 310, 250, -1));

        jButton_login_Pengguna.setBackground(new java.awt.Color(51, 153, 255));
        jButton_login_Pengguna.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton_login_Pengguna.setForeground(new java.awt.Color(255, 255, 255));
        jButton_login_Pengguna.setText("Login");
        jButton_login_Pengguna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_login_PenggunaActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_login_Pengguna, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 510, 160, 50));

        Password_login_pengguna.setBackground(new java.awt.Color(204, 255, 255));
        getContentPane().add(Password_login_pengguna, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 440, 250, -1));

        jButton_Kembali_Pengguna.setBackground(new java.awt.Color(51, 204, 255));
        jButton_Kembali_Pengguna.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Kembali_Pengguna.setText("kembali");
        jButton_Kembali_Pengguna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Kembali_PenggunaActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Kembali_Pengguna, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 570, 80, 30));

        buat_sekarangButton.setText("Buat Sekarang !");
        buat_sekarangButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buat_sekarangButtonActionPerformed(evt);
            }
        });
        getContentPane().add(buat_sekarangButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 580, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Belum Punya Akun ?");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 580, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/page/login pengguna.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void email_PenggunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_email_PenggunaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_email_PenggunaActionPerformed

    private void jButton_Kembali_PenggunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Kembali_PenggunaActionPerformed
        // TODO add your handling code here:
        Landing_home landing_home = new Landing_home();
        landing_home.setVisible(true);
        landing_home.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButton_Kembali_PenggunaActionPerformed

    private void buat_sekarangButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buat_sekarangButtonActionPerformed
        Register register = new Register();
        register.setVisible(true);
        register.setLocationRelativeTo(null);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_buat_sekarangButtonActionPerformed

    private void jButton_login_PenggunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_login_PenggunaActionPerformed

               try {
            String email = email_Pengguna.getText();
            String password = Password_login_pengguna.getText();

            if (email.equals("") || password.equals("")) {
                JOptionPane.showMessageDialog(null, "Email dan Password tidak boleh kosong!");
            } else {
                if (Pengguna.loginAccount(email, password)) {
                    Dasboard_pengguna dasboard_pengguna = new Dasboard_pengguna();
                    dasboard_pengguna.setVisible(true);
                    dasboard_pengguna.setLocationRelativeTo(null);
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(null, "Email dan password salah!");
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Terdapat Kesalahan: " + e.getMessage());
        }
    }//GEN-LAST:event_jButton_login_PenggunaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login_pengguna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login_pengguna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login_pengguna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login_pengguna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login_pengguna().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField Password_login_pengguna;
    private javax.swing.JButton buat_sekarangButton;
    private javax.swing.JTextField email_Pengguna;
    private javax.swing.JButton jButton_Kembali_Pengguna;
    private javax.swing.JButton jButton_login_Pengguna;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
