
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VIEW;
import Model.*;
import java.util.List;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Luqman
 */
public class Menu_pengguna extends javax.swing.JFrame {

    /**
     * Creates new form Searching_customer
     */
    public Menu_pengguna() {
         initComponents();
        Database.connect();
        tabel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    @SuppressWarnings("unchecked")
            final void tabel(){
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Halte Keberangkatan");
        model.addColumn("Halte Tiba");
        model.addColumn("Waktu Keberangkatan");
        model.addColumn("Waktu Tiba");
        
            try {
            Statement statement = Database.connection.createStatement();
            ResultSet resultSet = statement.executeQuery("SELECT * FROM jadwal_halte");

    while (resultSet.next()) {
        
        model.addRow(new Object[] {
            resultSet.getString("halte_keberangkatan"),
            resultSet.getString("halte_tiba"),
            resultSet.getString("waktu_keberangkatan"),
            resultSet.getString("waktu_tiba")
        });
         Table_menupengguna.setModel(model);
    } 
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Gagal memuat data!");
            }
         }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        halte_keberangkatan = new javax.swing.JTextField();
        halte_tiba = new javax.swing.JTextField();
        Button_searching = new javax.swing.JButton();
        jButton_Kmbali = new javax.swing.JButton();
        Refresh = new javax.swing.JButton();
        jComboBox_waktu_keberangkatan = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table_menupengguna = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1200, 750));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        halte_keberangkatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                halte_keberangkatanActionPerformed(evt);
            }
        });
        getContentPane().add(halte_keberangkatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 210, 350, -1));

        halte_tiba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                halte_tibaActionPerformed(evt);
            }
        });
        getContentPane().add(halte_tiba, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 250, 350, -1));

        Button_searching.setBackground(new java.awt.Color(51, 204, 255));
        Button_searching.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Button_searching.setForeground(new java.awt.Color(255, 255, 255));
        Button_searching.setText("Cari Rute");
        Button_searching.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_searchingActionPerformed(evt);
            }
        });
        getContentPane().add(Button_searching, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 330, 160, -1));

        jButton_Kmbali.setBackground(new java.awt.Color(204, 255, 255));
        jButton_Kmbali.setForeground(new java.awt.Color(102, 153, 255));
        jButton_Kmbali.setText("Kembali");
        jButton_Kmbali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_KmbaliActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_Kmbali, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 90, -1));

        Refresh.setText("Refresh");
        Refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshActionPerformed(evt);
            }
        });
        getContentPane().add(Refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 330, -1, -1));

        jComboBox_waktu_keberangkatan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "keberangkatan awal", "keberangkatan terakhir" }));
        jComboBox_waktu_keberangkatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_waktu_keberangkatanActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox_waktu_keberangkatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 290, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Halte Keberangkatan");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Sorting Waktu");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 290, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Halte Tujuan");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, -1, -1));

        Table_menupengguna.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Halte Keberangkatan", "Halte Tujuan", "Waktu Keberangkatan", "Waktu Tiba"
            }
        ));
        jScrollPane1.setViewportView(Table_menupengguna);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 390, 660, 230));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/page/searching pelanggan.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Button_searchingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_searchingActionPerformed
// Ambil input dari text field dan combo box
String halteKeberangkatan = halte_keberangkatan.getText().trim();
String halteTiba = halte_tiba.getText().trim();
    String selectedOption = jComboBox_waktu_keberangkatan.getSelectedItem().toString();
    String sortOrder = selectedOption.equalsIgnoreCase("keberangkatan awal") ? "ASC" : "DESC";

DefaultTableModel model = new DefaultTableModel();
model.addColumn("Halte Keberangkatan");
model.addColumn("Halte Tujuan");
model.addColumn("Waktu Keberangkatan");
model.addColumn("Waktu Tiba");

try {
    // Panggil metode pencarian dan sorting
    List<Jadwal_halte> hasil = Jadwal_halte.searchAndSortJadwalHalte(halteKeberangkatan, halteTiba, sortOrder);

    // Proses hasil pencarian dan sorting, tambahkan ke tabel
    for (Jadwal_halte jadwal : hasil) {
        model.addRow(new Object[]{
            jadwal.getHalte_keberangkatan(),
            jadwal.getHalte_tiba(),
            jadwal.getWaktu_keberangkatan(),
            jadwal.getWaktu_tiba()
        });
    }

    // Tampilkan hasil pada tabel
    Table_menupengguna.setModel(model);

    // Pesan jika hasil kosong
    if (hasil.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Tidak ada data yang ditemukan.");
    }
} catch (Exception e) {
    JOptionPane.showMessageDialog(null, "Gagal mencari dan menyortir data: " + e.getMessage());
}

          
    }//GEN-LAST:event_Button_searchingActionPerformed

    private void jComboBox_waktu_keberangkatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_waktu_keberangkatanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_waktu_keberangkatanActionPerformed

    private void jButton_KmbaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_KmbaliActionPerformed
        Dasboard_pengguna dasboard_pengguna = new Dasboard_pengguna();
        dasboard_pengguna.setVisible(true);
        dasboard_pengguna.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButton_KmbaliActionPerformed

    private void halte_keberangkatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_halte_keberangkatanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_halte_keberangkatanActionPerformed

    private void halte_tibaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_halte_tibaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_halte_tibaActionPerformed

    private void RefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshActionPerformed
       tabel();
    }//GEN-LAST:event_RefreshActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_pengguna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_pengguna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_pengguna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_pengguna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_pengguna().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_searching;
    private javax.swing.JButton Refresh;
    private javax.swing.JTable Table_menupengguna;
    private javax.swing.JTextField halte_keberangkatan;
    private javax.swing.JTextField halte_tiba;
    private javax.swing.JButton jButton_Kmbali;
    private javax.swing.JComboBox<String> jComboBox_waktu_keberangkatan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
